name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Evolution.Client/Evolution.Client.csproj

      - name: Build
        run: dotnet build src/Evolution.Client/Evolution.Client.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test tests/Evolution.Client.Tests/Evolution.Client.Tests.csproj --no-build --configuration Release

      - name: Pack
        run: dotnet pack src/Evolution.Client/Evolution.Client.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
